---
title: "Assignment2"
author: "Lukas_Spatz"
date: "23 11 2020"
output: html_document
---


#assign number to n
n <- 3

#1 if-then-else statement which prints “larger” if the number provided as variable n is larger than 1 
#and “equal or smaller” otherwise.
if (n>1) {
  print("larger")
} else {
  print("equal or smaller")
}

#2 Extent a copy of the above statement (i.e. copy the entire if-then-else statement and include it a second time in your script in order to preserve both versions) 
#which returns “equal” and “smaller” explicitly in addition to “larger”
if (n >1) {
  print("larger")
} else if (n==1) {
  print("equal")
} else if (n < 1) {
  print("smaller")
}

#3 Implement a if-then-else statement which prints “even” if the number provided as variable n 
#is even and which prints “odd” otherwise.

if (n %% 2 == 0) {
  print("even")
} else {
  print("odd")
}

#4 Copy the extended larger/equal/smaller if-then-else statement and include it 
#into a for loop which shows that all three options are actually implemented in a correct manner by iterating over n from a number which is smaller 1, 
#exactly 1 and larger than 1.
for(n in 0:2)
  if (n >1) 
 print("larger")
   else if (n==1) 
    print("equal")
   else if (n < 1) 
    print("smaller")
   
  